### PR TITLE
Added textColor option

### LINKED ISSUE #6: Font color
Hi Marcel,

could you please provide the possibility to change the font color for every method?
Or maybe the complete font settings? ;)

Thanks in advance!

### PR DESCRIPTION
**Pull request by ludolphus**
The showMessageWithColor and showMessageWithColorDuration now have an
extra parameter textColor to specify the color of the message text.
Should fix #6

### CODE REVIEW

**Comment by mpociot** [comment]
Thanks for the PR. Could you please add a default text color (black)?

Otherwise existing apps would crash because of the missing parameter.

**Comment by mpociot** [comment]
Oh and please update the example dictionary for the README functions too.

**Comment by ludolphus** [comment]
ok, done. another PR coming your way

**Comment by mpociot** [comment]
Great!

**Pull request merged**
